const {chromium}=require('/opt/codex/runtimes/cua/lib/node_modules/playwright');
const fs=require('fs'),path=require('path');
const project=path.resolve(__dirname,'..'),out=path.join(project,'test-output');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-crashpad-for-testing','--disable-crash-reporter','--no-zygote','--single-process']});
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+path.join(project,'app/src/main/assets/index.html'));
 const click=async(action)=>page.locator(`[data-action="${action}"]`).first().click();
 const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('liftlog-v1')));
 const assert=(test,msg)=>{if(!test)throw Error(msg);console.log('PASS '+msg);};
 await page.screenshot({path:path.join(out,'Liftlog-home.png'),fullPage:true});
 await click('start');await page.fill('#exercise-search','벤치');await click('pickExercise');await click('addPicked');
 assert((await read()).draft.exercises.length===1,'운동 검색 및 선택');
 await page.locator('[data-field="weight"]').first().fill('50');await page.locator('[data-field="reps"]').first().fill('8');await click('checkSet');
 let d=await read();assert(d.draft.exercises[0].sets[0].weightKg===50&&d.draft.exercises[0].sets[0].done,'세트 무게·횟수 및 완료');assert(d.timer&&d.timer.total===90,'세트 완료 자동 타이머');
 await click('timerToggle');const remaining=(await read()).timer.remaining;await page.waitForTimeout(1100);assert((await read()).timer.remaining===remaining,'타이머 일시 정지');await click('timerToggle');assert(!(await read()).timer.paused,'타이머 재개');await click('timerStop');
 await click('unit');assert(Math.abs(Number(await page.locator('[data-field="weight"]').first().inputValue())-110.23)<.01,'kg→lb 실제 환산');await click('unit');assert((await read()).draft.exercises[0].sets[0].weightKg===50,'단위 왕복 시 원본 무게 유지');
 await page.screenshot({path:path.join(out,'Liftlog-workout.png'),fullPage:true});
 await page.reload();assert(await page.locator('#session-name').isVisible(),'새로고침 시 진행 운동 복구');
 await page.fill('#workout-notes','오늘 첫 운동 완료');await click('finish');await click('saveWorkout');d=await read();assert(d.sessions.length===1&&d.draft===null&&d.sessions[0].exercises[0].sets.length===1,'완료한 세트만 영구 저장');
 assert(await page.locator('.calendar-date.has-record').count()===1,'캘린더 운동 표시');await page.screenshot({path:path.join(out,'Liftlog-calendar.png'),fullPage:true});
 await click('viewSession');assert(await page.getByText('50 kg × 8회').isVisible(),'저장 기록 상세 조회');await click('close');
 await page.locator('[data-page="insights"]').click();assert(await page.locator('.chart').count()===1,'실제 기록 성장 그래프');await page.screenshot({path:path.join(out,'Liftlog-insights.png'),fullPage:true});
 await page.locator('[data-page="settings"]').first().click();await page.selectOption('#goal-setting','5');await page.selectOption('#rest-setting','30');await page.locator('[data-unit="lb"]').click();d=await read();assert(d.settings.goal===5&&d.settings.rest===30&&d.settings.unit==='lb','설정 저장');
 const backup=JSON.stringify(d);await page.evaluate(raw=>window.importBackup(raw),backup);await click('confirmImport');assert((await read()).sessions.length===1,'백업 검증 및 복원');
 await page.evaluate(()=>window.importBackup('{"version":1,"sessions":[]}'));assert(await page.locator('#toast').innerText()==='유효한 리프트로그 백업 파일이 아닙니다.','손상 백업 거부');
 await page.locator('[data-page="routines"]').click();await click('start');await click('customExercise');await page.fill('#custom-name','케틀벨 스윙');await click('saveCustom');assert((await read()).customExercises.length===1,'사용자 운동 추가');await click('cancelWorkout');await click('confirmCancel');assert((await read()).draft===null&&(await read()).sessions.length===1,'진행 운동 취소 및 기존 기록 보존');
 await page.locator('[data-page="routines"]').click();await click('routine');assert((await read()).draft.exercises.length===4,'전신 루틴 바로 시작');await click('cancelWorkout');await click('confirmCancel');
 await page.evaluate(()=>window.quickStart());assert((await read()).draft!==null,'위젯 호출 경로 운동 시작');await click('close');
 await page.setViewportSize({width:320,height:720});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=320),'320px 화면 가로 넘침 없음');
 assert(errors.length===0,'브라우저 오류 없음');
 await browser.close();fs.writeFileSync(path.join(out,'test-results.txt'),'운동 선택, 세트 기록, 타이머, 단위 변환, 진행 복구, 캘린더, 성장 그래프, 설정, 백업, 사용자 운동, 루틴, 위젯 호출 경로 및 320px 레이아웃 브라우저 검증 통과.\nAndroid SDK 부재로 네이티브 컴파일 및 실기기 테스트는 수행하지 못함.\n');
})().catch(e=>{console.error(e);process.exit(1);});
